<Project Sdk="Microsoft.NET.Sdk.Worker">
  <ItemGroup>
    <PackageReference Include="IdGen" Version="3.0.7" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.12" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Systemd" Version="10.0.12" />
    <PackageReference Include="Microsoft.Extensions.Hosting.WindowsServices" Version="10.0.12" />
    <PackageReference Include="Microsoft.Extensions.Options" Version="10.0.12" />
    <PackageReference Include="Serilog.Extensions.Hosting" Version="10.0.0" />
    <PackageReference Include="Serilog.Sinks.Async" Version="2.1.0" />
    <PackageReference Include="Serilog.Sinks.Console" Version="6.1.1" />
    <PackageReference Include="Serilog.Sinks.File" Version="7.0.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\DH.Tools\DH.Tools.csproj" />
    <ProjectReference Include="..\DH.Events\DH.Events.csproj" />
    <ProjectReference Include="..\DH.Entity\DH.Entity.csproj" />
    <ProjectReference Include="..\DH.Controller\DH.Controller.csproj" />
  </ItemGroup>
  <PropertyGroup>
    <Version>1.0.0</Version>
  </PropertyGroup>
</Project>